# Generated by Django 5.2.1 on 2025-06-10 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("location", models.CharField(max_length=100)),
                (
                    "area",
                    models.PositiveIntegerField(help_text="Area in square meters"),
                ),
                ("rooms", models.PositiveIntegerField(default=1)),
                ("bathrooms", models.PositiveIntegerField(default=1)),
                (
                    "category",
                    models.CharField(
                        choices=[("sale", "بيع"), ("rent", "إيجار")],
                        default="sale",
                        max_length=10,
                    ),
                ),
                ("available_from", models.DateField(blank=True, null=True)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("villa", "Villa"),
                            ("penthouse", "Penthouse"),
                            ("basement", "Basement"),
                            ("roof", "Roof"),
                            ("building", "Building"),
                            ("mall", "Mall"),
                            ("office", "Office"),
                            ("clinic", "Clinic"),
                            ("duplex", "Duplex"),
                            ("land", "Land"),
                            ("Store", "Store"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "number_of_floors",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("units_count", models.PositiveIntegerField(blank=True, null=True)),
                ("has_elevator", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amenities",
                    models.TextField(blank=True, help_text="Comma-separated amenities"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="availabl?"),
                ),
                ("display_order", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="property_images/")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.property",
                    ),
                ),
            ],
        ),
    ]
