# Generated by Django 5.2.1 on 2025-06-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={"ordering": ["display_order"]},
        ),
    ]
