# Generated by Django 5.2.1 on 2025-06-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_alter_property_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="slug",
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
