# Generated by Django 5.2.1 on 2025-06-02 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_amenities_property_available_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم العمارة أو كود خاص بها', max_length=100)),
                ('number_of_floors', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.PositiveIntegerField(blank=True, help_text='رقم الطابق', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.building'),
        ),
    ]
