# Generated by Django 5.2.1 on 2025-06-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_building_property_floor_number_property_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='building',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
    ]
