# Generated by Django 5.2.1 on 2025-06-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_property_building_delete_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='floor_number',
        ),
        migrations.AddField(
            model_name='property',
            name='has_elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_floors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='units_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
