# Generated by Django 5.2.1 on 2025-06-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_property_floor_number_property_has_elevator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='availabl?'),
        ),
    ]
