# Generated by Django 5.2.1 on 2025-06-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_remove_property_image_propertyimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['display_order', '-id']},
        ),
        migrations.AddField(
            model_name='property',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('penthouse', 'Penthouse'), ('basement', 'Basement'), ('roof', 'Roof'), ('building', 'Building'), ('mall', 'Mall'), ('office', 'Office'), ('clinic', 'Clinic'), ('duplex', 'Duplex'), ('land', 'Land'), ('Store', 'Store')], max_length=20),
        ),
    ]
