# Generated by Django 5.1.3 on 2025-06-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_remove_property_image_propertyimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment"),
                    ("villa", "Villa"),
                    ("penthouse", "Penthouse"),
                    ("basement", "Basement"),
                    ("roof", "Roof"),
                    ("building", "Building"),
                    ("mall", "Mall"),
                    ("office", "Office"),
                    ("clinic", "Clinic"),
                    ("duplex", "Duplex"),
                    ("land", "Land"),
                    ("Store", "Store"),
                ],
                max_length=20,
            ),
        ),
    ]
