# Generated by Django 5.2.1 on 2025-06-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_property_options_property_display_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
        migrations.RemoveField(
            model_name='property',
            name='slug',
        ),
    ]
